### ISSUE TITLE
Long press difficult to trigger on real device

### ISSUE THREAD

**Issue by manuelkasper** [zacwest/ZSWTappableLabel#23]
The long press delegate method is difficult to trigger on a real device (vs. the simulator) because even the slightest movement of the finger while long-pressing a link will restart the 0.5 second timer.

Simply ignoring the UIGestureRecognizerStateChanged state in the longPress: method of ZSWTappableLabel appears to fix the issue.

**Comment by manuelkasper** [comment]
And I almost forgot to say: thank you very much for making this useful component available! Apart from this minor issue, everything is working fine "out-of-the-box" so far :)

**Comment by zacwest** [comment]
I think I see what you mean. I'm not sure ignoring `.Changed` is going to be best, because I still want the label to support dragging around between tappable regions.

I think a good solution may be that `beginLongPressAtIndex(_:)` doesn't invalidate/reset the timer if the movement is small within the same tappable region.
